name: Build and Deploy HTML to Production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build-and-deploy-to-barge-dot-org:
    runs-on: ubuntu-latest
    environment: barge.org
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: checkout source
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: 0.147.9
      - name: build site with hugo
        run: hugo --environment production
      - name: rsync 'public' to production host
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: burnett01/rsync-deployments@7.0.1
        with:
          path: public/
          remote_host: ${{ secrets.HOST }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: /var/www/newbarge/
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USERNAME }}
          switches: -avzr --delete --exclude=".??*,*~"
