name: Build and Deploy HTML to Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build-and-deploy-to-test-dot-bjrge-dot-org:
    runs-on: ubuntu-latest
    environment: test.bjrge.org
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: 0.139.2
      - name: build site with hugo
        run: hugo --environment staging
      # Note: Deploy _all_ changes, last one wins I guess?
      - name: rsync 'public' to test host
        uses: burnett01/rsync-deployments@7.0.1
        with:
          path: public/
          remote_host: ${{ secrets.HOST }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: /home/timshow/test.bjrge.org
          remote_user: ${{ secrets.USER }}
          switches: -avzr --delete --exclude=".??*,*~"
